### PR TITLE
Add AIRLOCK_PREFIX to modify csrf-cookie route prefix

### LINKED ISSUE #17: Unable to change route path
By default, the package loads the route into `/airlock/csrf-cookie`.

Since the application constantly accesses only the `/api` routes, I changed the parameter `baseURL` to `axios.defaults.baseURL = '/api';`

Now when you try to send a GET request to address `/airlock/csrf-cookie`, in fact the request is sent to `/api/airlock/csrf-cookie`.

It would be great to do one of the following options:

1. add the ability to specify the route prefix in file `config/airlock.php`;
2. change the route declaration method similar to `Passport::routes()`.

### PR DESCRIPTION
**Pull request by Te7a-Houdini**
Resolves #17

### CODE REVIEW

**Comment by rennokki** [comment]
The config should have a default value?

**Comment by Te7a-Houdini** [comment]
@rennokki i don't think so . cause if no default value presented the route will be without prefix

**Comment by mbougarne** [comment]
Why not to add **prefix** value directly in the config file? ``` 'prefix' => 'api', ``` 
``` php
Route::get(
            '/airlock/csrf-cookie',
            CsrfCookieController::class.'@show'
        )->middleware('web')->prefix(config('airlock.prefix'))
```

**Comment by Te7a-Houdini** [comment]
@mbougarne i just followed [doc example](https://laravel.com/docs/6.x/routing#route-group-prefixes)

**Comment by meSingh** [comment]
@Te7a-Houdini A better implementation will be to have it like this: 

```
/*
|--------------------------------------------------------------------------
| Airlock Prefix
|--------------------------------------------------------------------------
|
| This prefix will be used when hiting initialize CSRF protection route for the application.
|
*/

'route_prefix' => env('AIRLOCK_ROUTE_PREFIX', 'airlock'),
```

```
Route::get(
    config('airlock.prefix') . '/csrf-cookie',
    CsrfCookieController::class.'@show'
)->middleware('web');
```

**Comment by taylorotwell** [comment]
Tweaked this implementation. You can add a prefix configuration option now if you want.

**Comment by emargareten** [comment]
@taylorotwell Is there a reason why there isn't a prefix option in the config file by default?

**Pull request closed without merging**
